"""add avatar_path for User and img_cover_uri server_default for Game

Revision ID: ab91d314bd77
Revises: aa3d0c267a55
Create Date: 2026-04-22 00:29:38.186855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab91d314bd77'
down_revision = 'aa3d0c267a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('cover_image_uri',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'/static/upload/defaults/defaultcover.jpg'::character varying"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=256), server_default='/static/upload/defaults/defaultavatar.jpg', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('cover_image_uri',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'/static/upload/defaultcover.jpg'::character varying"))

    # ### end Alembic commands ###
