"""add avatar_path for Usert and cover_path server_default for Game

Revision ID: c2dc26c7dabe
Revises: aa3d0c267a55
Create Date: 2026-04-22 23:59:53.732510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dc26c7dabe'
down_revision = 'aa3d0c267a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_path', sa.String(length=256), server_default='defaultcover.jpg', nullable=True))
        batch_op.drop_column('cover_image_uri')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=256), server_default='defaultavatar.jpg', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_uri', sa.VARCHAR(), server_default=sa.text("'/static/upload/defaultcover.jpg'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('cover_path')

    # ### end Alembic commands ###
